import "mobx-react-lite/batchingForReactDom";
import React from "react";
import { createRoot } from "react-dom/client";
import { HashRouter } from "react-router-dom";
import { Toaster } from "sonner";
import Container from "./container";
import "./index-compiled.css"; // generated by tailwindcss; see package.jsons scripts
import "./prism-code-theme.css";

const root = createRoot(document.getElementById("app")!);

root.render(
  <>
    <HashRouter>
      <Toaster
        theme="light"
        duration={3000}
        position="bottom-right"
        toastOptions={{
          classNames: {
            toast:
              "px-2 py-4 group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground group-[.toaster]:border-border group-[.toaster]:shadow-lg",
            description: "group-[.toast]:text-muted-foreground",
            actionButton:
              "group-[.toast]:bg-primary group-[.toast]:text-primary-foreground",
            cancelButton:
              "group-[.toast]:bg-muted group-[.toast]:text-muted-foreground",
          },
        }}
      />
      <Container />
    </HashRouter>
  </>,
);
