# Workflow for code checks
name: Check code

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --ignore-scripts
      - run: bash scripts/lint.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: bun install --ignore-scripts
      - name: Run tests
        run: bun run test
